### ISSUE TITLE
Site CSS is broken

### ISSUE THREAD

**Issue by peterhurford** [impct/impct.github.io#23]
@patbl noted that this was because the site was recently rebuilt using a new major version, which broke the asset paths. It just needs to be rebuilt with a 2.x version:

```
gem install jekyll --version=2.5.3
jekyll _2.5.3_ build
```

**Comment by peterhurford** [comment]
@tog22

**Comment by tog22** [comment]
My last commit fixed it in a good way! (The previous one also fixed it, but in a hacky way.)

@patbl gave an enormous amount of help!

**Comment by peterhurford** [comment]
👍

**Comment by tog22** [comment]
❤️  Patrick

**Comment by tog22** [comment]
(❤️  Peter too, of course)

**Comment by tog22** [comment]
FYI @patbl (and @OAGr and @peterhurford), my fix doesn't work on localhost, where we have the same error - ASSET_PATH doesn't get layout.theme.name so internal CSS and JS URLS output wrong. E.g. Patrick just added a script which on http://dotimpact.im/focusprojects/newsletter.html#More gets output:

`<script src="/assets/themes/dotimpact/resources/site/link_table_of_contents.js"></script>`

But on http://127.0.0.1:4000/focusprojects/newsletter.html#More (served with `jekyll _2.5.3_ serve`), it outputs:

(like the `<script src="/assets/themes//resources/site/link_table_of_contents.js"></script>`

I can't afford to fix this myself, so am leaving the issue closed with this note.

**Comment by tog22** [comment]
(Googling quickly had turned up no way to set a hardcoded ASSET_PATH in _includes/JB/setup if on localhost.)

**Comment by patbl** [comment]
I think using a more-recent version of Jekyll in dev should help.

```
gem uninstall jekyll
gem install jekyll
jekyll build
jekyll serve
```

**Comment by tog22** [comment]
I'll have to leave that to you to play with if you want - which would help,
don't get me wrong, it's just we don't have time for this!

On 18 June 2016 at 15:51, Patrick Brinich-Langlois <notifications@github.com
